
# The name of your project. This will be used to generate the project id.
project_id = "hvqdzrztwjegbtpixmke"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://hvqdzrztwjegbtpixmke.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.razorpay-payment]
verify_jwt = true
