
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvqdzrztwjegbtpixmke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2cWR6cnp0d2plZ2J0cGl4bWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTY2OTksImV4cCI6MjA2MzQ5MjY5OX0.G-2odc_j3IAVWYouzyyoLTbIhwszzOIWdH2_5yf52SY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

// Add session validation helper
export const validateSession = async () => {
  try {
    const { data: { session }, error } = await supabase.auth.getSession();
    if (error) {
      console.error('❌ Session validation error:', error);
      await supabase.auth.signOut();
      return null;
    }
    return session;
  } catch (error) {
    console.error('❌ Session validation failed:', error);
    await supabase.auth.signOut();
    return null;
  }
};
